Not all symlinks are directories
Resolving this error:
error: Error: Not a directory (os error 20), readdir '/private/var/tmp/_bazel_work/2e7133aff2657e0e914d177b41c7f8d8/execroot/_main/bazel-out/darwin-fastbuild/bin/revision-bzl/lcd/generated/seed.graphql' for path "/private/var/tmp/_bazel_work/2e7133aff2657e0e914d177b41c7f8d8/execroot/_main/bazel-out/darwin-fastbuild/bin/revision-bzl/lcd/generated/seed.graphql"

Caused by this code:
```
for await (const entry of walk(/private/var/tmp/_bazel_work/2e7133aff2657e0e914d177b41c7f8d8/sandbox/darwin-sandbox/168/execroot/_main/bazel-out/darwin-fastbuild/bin/revision-bzl/lcd/, { includeFiles: true, exts: [".ts"], includeDirs: true, maxDepth: 20, followSymlinks: true })) {
    console.log(entry.path);
    // assert(entry.isFile);
  }
```

I believe that the symlink'd files are created during bazel's build process, since I cannot find the sandbox directory but the execroot contents match.